### ISSUE TITLE
Make document attachment button clickable

### ISSUE THREAD

**Issue by georgimld** [openkfw/TruBudget#1125]
## Description 💡

The attachement button on a workflowitem is currently not clickable, the only behavior it has is a tooltip shown when hovering over the button with the mouse. (Screenshot below)
![image](https://user-images.githubusercontent.com/48566702/165489636-33d888bc-1731-409e-b637-51cce5c0fb56.png)

The task in this issue would be to make the button clickable so that when it is clicked the workflowitem dialog is opened on the "documents" tab, as seen in the screenshot below:

<img width="568" alt="image" src="https://user-images.githubusercontent.com/48566702/165490004-70b75156-f9c3-48b2-b588-6be364289ef0.png">

## TODOs
- [x] check how the dialog is opened when the "info" button is clicked
- [x] check how to switch to the "documents" tab in the dialog
- [x] implement an action that opens the dialog on the correct tab when the "attachement" button is clicked
