### ISSUE TITLE
Subtask of #1339: Update @fastify/swagger in api

### ISSUE THREAD

**Issue by SamuelPull** [openkfw/TruBudget#1344]
- [x] I have searched the [issues](https://github.com/openkfw/TruBudget/issues) of this repository and believe that this is not a duplicate.

## Description 😯

Breaking changes in the most recent version 8.x.x require additional refactoring.

- [ ] Update @fastify/swagger in api to the most recent version
- [ ] Fix breaking changes (see https://github.com/fastify/fastify-swagger/blob/master/MIGRATION.md)
