### ISSUE TITLE
Subtask of #1339 - Update frontend npm packages

### ISSUE THREAD

**Issue by SamuelPull** [openkfw/TruBudget#1346]
- [x] I have searched the [issues](https://github.com/openkfw/TruBudget/issues) of this repository and believe that this is not a duplicate.

## Description 😯 

Npm packages should be updated. In case of deprecated/not maintained libraries, it might be better to investigate and discuss alternatives in a separate issue.

- [x] react-data-table-component  7.5.2    ❯  7.5.3    https://github.com/jbetancur/react-data-table-component#readme
- [x] react-redux                 8.0.2    ❯  8.0.5    https://github.com/reduxjs/react-redux
- [x] redux                       4.2.0    ❯  4.2.1    http://redux.js.org
- [x] redux-saga                  1.2.1    ❯  1.2.3    https://redux-saga.js.org/
- [x] styled-components           5.3.6    ❯  5.3.9    https://styled-components.com
  
 Minor Update New backwards-compatible features.
- [x] @babel/runtime                           7.18.9  ❯  7.21.0   https://babel.dev/docs/en/next/babel-runtime
- [x] @date-io/date-fns                        2.15.0  ❯  2.16.0   https://github.com/dmtrKovalenko/date-io#readme
- [x] @date-io/dayjs                           2.15.0  ❯  2.16.0   https://github.com/dmtrKovalenko/date-io#readme
- [x] @mui/icons-material                      5.8.4   ❯  5.11.16  https://mui.com/material-ui/material-icons/
- [x] @mui/material                            5.10.1  ❯  5.12.0   https://mui.com/material-ui/getting-started/overview/
 - [x] @mui/system                              5.10.1  ❯  5.12.0   https://mui.com/system/getting-started/overview/
 - [x] @reduxjs/toolkit                         1.8.5   ❯  1.9.4    https://redux-toolkit.js.org
 - [x] @babel/register devDep                   7.18.9  ❯  7.21.0   https://babel.dev/docs/en/next/babel-register
 ~~@typescript-eslint/eslint-plugin devDep  5.33.1  ❯  5.58.0   https://github.com/typescript-eslint/typescript-eslint#readme~~
~~@typescript-eslint/parser devDep         5.33.1  ❯  5.58.0   https://github.com/typescript-eslint/typescript-eslint#readme~~
- [x] eslint devDep                            8.22.0  ❯  8.38.0   https://eslint.org
- [x] eslint-config-prettier devDep            8.5.0   ❯  8.8.0    https://github.com/prettier/eslint-config-prettier#readme
- [x] eslint-plugin-import devDep              2.26.0  ❯  2.27.5   https://github.com/import-js/eslint-plugin-import
- [x] eslint-plugin-jsx-a11y devDep            6.6.1   ❯  6.7.1    https://github.com/jsx-eslint/eslint-plugin-jsx-a11y#readme
- [x] eslint-plugin-react devDep               7.30.1  ❯  7.32.2   https://github.com/jsx-eslint/eslint-plugin-react
- [x] prettier devDep                          2.7.1   ❯  2.8.7    https://prettier.io
  
 Major Update Potentially breaking API changes. Use caution.
- [x] axios              0.27.2  ❯  1.3.5   https://axios-http.com
- [x] chart.js           3.9.1   ❯  4.2.1   https://www.chartjs.org
- [x] downshift          6.1.9   ❯  7.6.0   https://downshift-js.com
- [x] history            4.10.1  ❯  5.3.0   https://github.com/remix-run/history#readme
- [x] immutable          3.8.2   ❯  4.3.0   https://immutable-js.com
- [x] query-string       7.1.1   ❯  8.1.0   https://github.com/sindresorhus/query-string#readme
 - [x] react-chartjs-2    4.3.1   ❯  5.2.0   https://github.com/reactchartjs/react-chartjs-2
 - [x] react-router       5.3.3   ❯  6.10.0  https://github.com/remix-run/react-router#readme
 - [x] react-router-dom   5.3.3   ❯  6.10.0  https://github.com/remix-run/react-router#readme
 - [x] typescript devDep  4.7.4   ❯  5.0.4   https://www.typescriptlang.org/
  
 Non-Semver Versions less than 1.0.0, caution.
- [x] content-disposition-attachment  0.2.0   ❯  0.3.1   https://github.com/lujjjh/content-disposition-attachment#readme
- [x] react-highlight-words           0.18.0  ❯  0.20.0  https://github.com/bvaughn/react-highlight-words#readme
- [x] vanilla-jsoneditor              0.6.4   ❯  0.17.0  https://jsoneditoronline.org has follow up task #1361
