### ISSUE TITLE
oss refactor-tracker

### ISSUE THREAD

**Issue by phpai** [openkfw/TruBudget#143]
In GitLab by @kevinbader on Mar 20, 2019, 09:31

@gonzochic @mathiashoeld @Stezido 

# Milestone 1.0.0-beta.9

- [x]  workflowitem.validateDocument

# Milestone 1.0.0-opensource

- [x]  global.listPermissions
- [x]  global.grantPermission
- [x]  global.grantAllPermissions
- [x]  global.revokePermission
- [x]  global.createProject
- [x]  global.createUser
- [x]  global.createGroup
- [x]  user.authenticate
- [x]  user.view
- [x]  group.addUser
- [x]  group.removeUser
- [x]  project.intent.listPermissions
- [x]  project.intent.grantPermission
- [x]  project.intent.revokePermission
- [x]  project.viewSummary
- [x]  project.viewDetails
- [x]  project.assign
- [x]  project.update
- [x]  project.close
- [x]  project.createSubproject
- [x]  project.viewHistory
- [x]  project.budget.updateProjected
- [x]  project.budget.deleteProjected
- [x]  subproject.intent.listPermissions 
- [x]  subproject.intent.grantPermission 
- [x]  subproject.intent.revokePermission 
- [x]  subproject.list
- [x]  subproject.viewDetails
- [x]  subproject.assign
- [x]  subproject.update 
- [x]  subproject.close 
- [x]  subproject.createWorkflowitem
- [x]  subproject.reorderWorkflowitems 
- [x]  subproject.viewHistory 
- [x]  subproject.budget.updateProjected 
- [x]  subproject.budget.deleteProjected 
- [x]  workflowitem.intent.listPermissions 
- [x]  workflowitem.intent.grantPermission
- [x]  workflowitem.intent.revokePermission 
- [x]  workflowitem.view
- [x]  workflowitem.assign
- [x]  workflowitem.update
- [x]  workflowitem.close
- [x]  notification.list
- [x]  notification.markRead
- [x]  notification.create

# Excluded

There's currently not much to gain from refactoring those endpoints, which work reliably right now and don't contain any business rules:

- [ ]  network.registerNode
- [ ]  network.list
- [ ]  network.listActive
- [ ]  network.voteForPermission
- [ ]  network.approveNewOrganization
- [ ]  network.approveNewNodeForExistingOrganization

**Comment by phpai** [comment]
In GitLab by @kevinbader on Mar 20, 2019, 09:33

marked the task **project.assign** as completed

**Comment by phpai** [comment]
In GitLab by @kevinbader on Mar 20, 2019, 09:33

marked the task **project.close** as completed

**Comment by phpai** [comment]
In GitLab by @kevinbader on Mar 20, 2019, 09:33

marked the task **project.update** as completed

**Comment by phpai** [comment]
In GitLab by @kevinbader on Mar 20, 2019, 09:33

marked the task **project.budget.deleteProjected** as completed

**Comment by phpai** [comment]
In GitLab by @kevinbader on Mar 20, 2019, 09:34

marked the task **project.budget.updateProjected** as completed

**Comment by phpai** [comment]
In GitLab by @kevinbader on Mar 20, 2019, 09:34

marked the task **group.addUser** as completed

**Comment by phpai** [comment]
In GitLab by @kevinbader on Mar 20, 2019, 09:34

marked the task **group.removeUser** as completed

**Comment by phpai** [comment]
In GitLab by @kevinbader on Mar 20, 2019, 09:34

marked the task **user.view** as completed

**Comment by phpai** [comment]
In GitLab by @kevinbader on Mar 20, 2019, 09:34

marked the task **user.authenticate** as completed

**Comment by phpai** [comment]
In GitLab by @kevinbader on Mar 20, 2019, 09:34

marked the task **global.createGroup** as completed

**Comment by phpai** [comment]
In GitLab by @kevinbader on Mar 20, 2019, 09:34

marked the task **global.createUser** as completed

**Comment by phpai** [comment]
In GitLab by @kevinbader on Mar 20, 2019, 09:34

marked the task **global.createProject** as completed

**Comment by phpai** [comment]
In GitLab by @mathiashoeld on Mar 20, 2019, 09:35

changed the description

**Comment by phpai** [comment]
In GitLab by @kevinbader on Mar 20, 2019, 09:35

marked the task **global.grantAllPermissions** as completed

**Comment by phpai** [comment]
In GitLab by @kevinbader on Mar 20, 2019, 09:35

marked the task **global.revokePermission** as completed

**Comment by phpai** [comment]
In GitLab by @mathiashoeld on Mar 20, 2019, 09:35

marked the task **subproject.viewDetails** as completed

**Comment by phpai** [comment]
In GitLab by @kevinbader on Mar 20, 2019, 09:35

marked the task **global.grantPermission** as completed

**Comment by phpai** [comment]
In GitLab by @mathiashoeld on Mar 20, 2019, 09:35

marked the task **subproject.assign** as completed

**Comment by phpai** [comment]
In GitLab by @kevinbader on Mar 20, 2019, 09:35

marked the task **project.viewSummary** as completed

**Comment by phpai** [comment]
In GitLab by @kevinbader on Mar 20, 2019, 09:35

marked the task **project.viewDetails** as completed

**Comment by phpai** [comment]
In GitLab by @kevinbader on Mar 20, 2019, 09:35

marked the task **project.intent.grantPermission** as completed

**Comment by phpai** [comment]
In GitLab by @kevinbader on Mar 20, 2019, 09:35

marked the task **project.intent.revokePermission** as completed

**Comment by phpai** [comment]
In GitLab by @mathiashoeld on Mar 20, 2019, 09:37

changed the description

**Comment by phpai** [comment]
In GitLab by @kevinbader on Mar 20, 2019, 09:38

marked the task **project.viewHistory** as completed

**Comment by phpai** [comment]
In GitLab by @kevinbader on Mar 20, 2019, 09:38

marked the task **project.createSubproject** as completed

**Comment by phpai** [comment]
In GitLab by @kevinbader on Mar 20, 2019, 09:39

marked the task **subproject.list** as completed

**Comment by phpai** [comment]
In GitLab by @kevinbader on Mar 20, 2019, 09:39

marked the task **notification.list** as completed

**Comment by phpai** [comment]
In GitLab by @kevinbader on Mar 20, 2019, 09:39

marked the task **notification.markRead** as completed

**Comment by phpai** [comment]
In GitLab by @kevinbader on Mar 20, 2019, 09:39

marked the task **notification.create** as completed

**Comment by phpai** [comment]
In GitLab by @mathiashoeld on Mar 20, 2019, 10:22

marked the task **subproject.intent.grantPermission **MATHIAS**** as completed

**Comment by phpai** [comment]
In GitLab by @gonzochic on Mar 20, 2019, 10:23

changed the description

**Comment by phpai** [comment]
In GitLab by @mathiashoeld on Mar 20, 2019, 10:35

marked the task **subproject.intent.revokePermission **MATHIAS**** as completed

**Comment by phpai** [comment]
In GitLab by @mathiashoeld on Mar 20, 2019, 11:19

marked the task **subproject.intent.listPermissions **MATHIAS**** as completed

**Comment by phpai** [comment]
In GitLab by @mathiashoeld on Mar 20, 2019, 11:38

changed the description

**Comment by phpai** [comment]
In GitLab by @mathiashoeld on Mar 20, 2019, 11:39

marked the task **global.listPermissions** as completed

**Comment by phpai** [comment]
In GitLab by @gonzochic on Mar 20, 2019, 13:01

marked the task **workflowitem.assign** as completed

**Comment by phpai** [comment]
In GitLab by @gonzochic on Mar 20, 2019, 13:02

marked the task **workflowitem.view** as completed

**Comment by phpai** [comment]
In GitLab by @kevinbader on Mar 20, 2019, 13:35

marked the task **workflowitem.update **KEVIN**** as completed

**Comment by phpai** [comment]
In GitLab by @kevinbader on Mar 20, 2019, 13:36

marked the task **workflowitem.update **KEVIN**** as incomplete

**Comment by phpai** [comment]
In GitLab by @mathiashoeld on Mar 20, 2019, 14:42

marked the task **subproject.close **MATHIAS**** as completed

**Comment by phpai** [comment]
In GitLab by @kevinbader on Mar 20, 2019, 15:22

marked the task **workflowitem.update **KEVIN**** as completed

**Comment by phpai** [comment]
In GitLab by @kevinbader on Mar 20, 2019, 15:36

marked the task **subproject.budget.updateProjected **KEVIN**** as completed

**Comment by phpai** [comment]
In GitLab by @kevinbader on Mar 20, 2019, 15:36

marked the task **subproject.budget.deleteProjected **KEVIN**** as completed

**Comment by phpai** [comment]
In GitLab by @kevinbader on Mar 20, 2019, 15:36

marked the task **project.intent.listPermissions** as completed

**Comment by phpai** [comment]
In GitLab by @kevinbader on Mar 20, 2019, 15:37

marked the task **subproject.createWorkflowitem** as completed

**Comment by phpai** [comment]
In GitLab by @mathiashoeld on Mar 20, 2019, 15:57

marked the task **subproject.update **MATHIAS**** as completed

**Comment by phpai** [comment]
In GitLab by @gonzochic on Mar 20, 2019, 16:29

marked the task **subproject.viewHistory **MATHIAS**** as completed

**Comment by phpai** [comment]
In GitLab by @gonzochic on Mar 20, 2019, 17:00

marked the task **workflowitem.intent.grantPermission **STEFAN**** as completed

**Comment by phpai** [comment]
In GitLab by @gonzochic on Mar 20, 2019, 17:00

marked the task **workflowitem.intent.revokePermission **STEFAN**** as completed

**Comment by phpai** [comment]
In GitLab by @gonzochic on Mar 20, 2019, 17:00

marked the task **workflowitem.intent.listPermissions **STEFAN**** as completed

**Comment by phpai** [comment]
In GitLab by @gonzochic on Mar 20, 2019, 17:00

marked the task **subproject.reorderWorkflowitems **ROMAN**** as completed

**Comment by phpai** [comment]
In GitLab by @gonzochic on Mar 20, 2019, 17:30

marked the task **workflowitem.close **ROMAN**** as completed

**Comment by phpai** [comment]
In GitLab by @Stezido on Mar 21, 2019, 14:08

changed the description

**Comment by phpai** [comment]
In GitLab by @kevinbader on Mar 22, 2019, 10:52

changed the description

**Comment by phpai** [comment]
In GitLab by @kevinbader on Mar 22, 2019, 10:52

changed the description
