### ISSUE TITLE
Create changelog guidelines, move release process documentation

### ISSUE THREAD

**Issue by Stezido** [openkfw/TruBudget#392]
### Description
Our Changelog does follow guidlines but they are not documented. We should add a documentation for that. The changelog should also describe the current changes in detail. An example of describing details of our changes is the [Changelog of Elixir](https://github.com/elixir-lang/elixir/blob/v1.9.1/CHANGELOG.md).

So our guildines should be a combination of the description part of elixir's changelog and our changes linked with github issues.

### TODOs
- [ ] Move documentation for release process (from adr git-branching-model) to a new location/file
- [ ] Write guidelines for our changelog and link them in the release process
- [ ] Update 1.4.0 Changelog as written in [Tag description](https://github.com/openkfw/TruBudget/releases/tag/v1.4.0)

**Comment by Stezido** [comment]
We decided to keep the Changelog as simple as possible. For detailed information the documentation of Trubudget is improving while introducing new features and fixes. The release process in detail is also not important for external users/contributors so we decided to skip the implementation of this issue
