### ISSUE TITLE
api: user can list project permissions without project.intent.listPermissions

### ISSUE THREAD

**Issue by Stezido** [openkfw/TruBudget#393]
### Description
The endpoint project.intent.listPermissions seems to only check for the user's viewSummary permission, but ignores his/her project.intent.listPermissions.

### TODO

- [ ] Fix project.intent.listPermissions endpoint
- [ ] Check/Fix subproject.intent.listPermissions
- [ ] Check/Fix workflowitem.intent.listPermissions
