### ISSUE TITLE
e2e: Write tests for workflowitem batch edit

### ISSUE THREAD

**Issue by Stezido** [openkfw/TruBudget#404]
### Description
There are no tests for the workflowitem batch edit feature. Other features could break it.

### Todo
Write e2e-tests:
- [x] Reordering of open workflowitems is done on submit
- [x] Reordering button is disabled when user has no permission or there are only closed workflowitems 
- [ ] "Reordering mode" is enabled but closed workflowitems can't  be reordered
- [ ] "Reordering mode" is enabled but workflowitems can't  be reordered if there are redacted ones in between
- [x] Batch edit drawer opens on selecting the first workflowitem in reordering mode
- [ ] Batch edit drawer views current permissions/assignee if they are the same
- [ ] Preview dialog opens on clicking the drawers update button
- [ ] Preview dialog shows right actions including revoking actions (because grant permissions via batch edit overwrites the permissions of a workflowitem)
- [x] Changes will be applied correctly
 
reference to #408

**Comment by daniel-arnauer** [comment]
Issue has not been resolved yet
