### ISSUE TITLE
ui: Preview and confirmation dialog should use the same executeactions saga

### ISSUE THREAD

**Issue by Stezido** [openkfw/TruBudget#408]
### Description
Preview and confirmation dialog are currently using different sagas with the same goal. -> execute actions. The preview dialog should use the executeActions method and the actions should be in the same format. The behavior of executing actions in the batch-edit feature (preview dialog) should be similar to the permissions dialog.

#### Description
Currently the bath-edit feature is not acting in a expecting way for the user. It overwrites any permission the user wants to edit. For example if 7 user have view permissions on the selected workflowitems the batch edit feature would first revoke all 7 permissions and then grant view permissions to all users selected. A user is expected to only affect the users he/she selected.

*Hint: It's not possible to show the permissions in the batch-edit-drawer because multiple workflowitems could have different ones* 

#### Implementation
Separate grant and revoke permissions by offering a two part toggle button (grant/revoke) in the drawer. This way a check can be implemented if a selected user has already granted/revoked a permission or not.

### TODO

- [ ] Make both using the same actions format
- [ ] Make both use the same saga method
- [ ] The saga method should use other sagas instead of own api calls
- [ ]  Implement two part toggle button and separate grant/revoke permissions
 
reference to #404

**Comment by galethil** [comment]
Closing due to inactivity
