### ISSUE TITLE
ui: Move "view permissions"-permission to "View permission" section

### ISSUE THREAD

**Issue by Stezido** [openkfw/TruBudget#613]
### Description
Currently the "view permissions"-permission(e.g. `project.intent.listPermissions`) in the permission dialog is located in the "Admin permission"-section. Since the "view permission" permission is a View permission it should be located in the "View permission"-section

### TODO

- [ ] Move the "view permissions"-permission to the "View Permission"-section on project level
- [ ] Move the "view permissions"-permission to the "View Permission"-section on subproject level
- [ ] Move the "view permissions"-permission to the "View Permission"-section on workflowitem level
