### ISSUE TITLE
ui: Dropdown of user selections should include a close button

### ISSUE THREAD

**Issue by Stezido** [openkfw/TruBudget#614]
### Description
Currently to close the user selections a user has to click outsided of the selection. This is not very user friendly. The user selection should include a button which closes the selection.

### Solution
Create a `x`-Symbol-Button 

### TODO

- [x] Check user selection in permission dialog of all resources 
- [x] Check user selection in assignee field of all resources
- [x] Check batch editing assignee and permission fields
- [x] Check groups user selection on user/groups page
- [x] Check workflowitem create (assignee)
- [x] Check subproject create (validator)
- [ ] Adapt/Create e2e-tests 
- [x] Assignee Selection Search field should be aligned with the user list (left)
