### ISSUE TITLE
e2e: Write tests for closing projects/subprojects/workflowitems

### ISSUE THREAD

**Issue by daniel-arnauer** [openkfw/TruBudget#623]
Write e2e tests for closing  projects/subprojects/workflowitems where only the assignee is allowed to close it

### Solution 
Create extra close.spec files for project/subproject

### TODO

- [x] Create project close e2e-tests
- [x] Create subproject close e2e-tests
- [x] Check workflowitem close e2e-tests
