### ISSUE TITLE
ui: Combine the UserSelection and PermissionSelection components

### ISSUE THREAD

**Issue by georgimld** [openkfw/TruBudget#624]
Even though the AssigneeSelection, UserSelection and the PermissionSelection components look the same in the ui, they are separate components. It should be analysed which components can use a generic one.

### TODO
- [ ] Analyse PermissionSelection, UserSelection and AssigneeSelection and decide if a generic User seclection component could be used
- [ ] Create TODOs for the refactoring
- [ ] Write e2e-tests or update them
