### ISSUE TITLE
Run E2E tests with Docker containers - 5SP

### ISSUE THREAD

**Issue by m-janos** [openkfw/TruBudget#651]
- [x] I have searched the [issues](https://github.com/openkfw/TruBudget/issues) of this repository and believe that this is not a duplicate.

## Summary 💡

 - Running E2E should be possible with containerized mode (e.g. after running `sh scripts/start-master-node.sh` or running each service in container individually) on local development machine
 - Fix host name, expose container ports to be accessible publicly,  if needed

## Examples 🌈

 - After implementation the process should looks like:
  1. `sh scripts/start-and-provision-master-node.sh`
  2. (another terminal, e2e-test folder) `npm run e2etest` 

## Motivation 🔦
 - To make writing E2E tests fast and straightforward without worried about running each service separately

## Subtask Checklist ✔️
- [ ] Create Docker Compose file and Bash file for single test run
- [ ] Run all tests
