### ISSUE TITLE
Github actions improvements 

### ISSUE THREAD

**Issue by Stezido** [openkfw/TruBudget#659]
- [x] I have searched the [issues](https://github.com/openkfw/TruBudget/issues) of this repository and believe that this is not a duplicate.

## Summary 💡

Currently github actions work but following improvements can be made

### TODO

 - [ ] build/push docker images with github action instead via script
 - [ ] only run necessary jobs (e.g. if I changed the frontend only - only frontend should be audited/tested for the pull_request)
 - [ ] rename env vars on e2e-test ci-cd side 
 - [ ] add linting jobs

## Motivation 🔦

The Todos provide consistency/ faster pipeline execution

**Comment by Stezido** [comment]
Following subtask should be completed to ensure linting jobs are working properly:
 -  Fix eslint issues #787

**Comment by daniel-arnauer** [comment]
Closed in #794
