### ISSUE TITLE
ui: Introduce new field "due date" workflowitem level

### ISSUE THREAD

**Issue by phpai** [openkfw/TruBudget#71]
In GitLab by @moise.djanhan on Jan 27, 2019, 23:42

Show deadlines per workflow and send notifications in case of retard

#### Description
Add OPTIONAL data point "due date" (or "target date") to workflowitems.
Additionally: It would be ideal if the customer is notified (notification/email) if the due date has passed

#### Todo
- [x] Implement new field on api level.
- [x] Check backwards compatibility
- [x] Create unit tests
- [x] Create new optional field in workflowitem creation and edit dialog
- [x] Mark red if due date has passed
- [x] Create e2e-tests 
- [ ] Create follow up issue for email notifications (To use the email service a notification has to be created on api level)

**Comment by phpai** [comment]
In GitLab by @mathiashoeld on Jan 31, 2019, 15:23

Add OPTIONAL data point "due date" (or "deadline") to workflowitems.
Additionally: It would be ideal if the customer is notified (notification/email) if the deadline is passed

**Comment by phpai** [comment]
In GitLab by @kevinbader on Feb 25, 2019, 10:56

assigned to @kevinbader

**Comment by phpai** [comment]
In GitLab by @lennart.ploen on Mar 12, 2019, 14:04

We have reserved this issue for phase 2.

**Comment by phpai** [comment]
In GitLab by @kevinbader on Mar 18, 2019, 08:57

removed milestone

**Comment by daniel-arnauer** [comment]
Workflowitems have to be closed in a serial way, so the due-date of the next workflowitem has to be later than the due-date of the previous workflow item (at least the same date or later).
Should this validation be also implemented?

**Comment by mathiashoeld** [comment]
> Workflowitems have to be closed in a serial way, so the due-date of the next workflowitem has to be later than the due-date of the previous workflow item (at least the same date or later).
> Should this validation be also implemented?

from my point of view the answer is yes. 
let's take the counter example: i have two workflowitems (wf1 and wf2) and they have the following due dates:
 
- wf1: 10.01.2020
- wf2: 01.01.2020

then wf2 needs to be closed before the due date of wf1. since wf2 cannot be closed before wf1, it needs to be put before wf1. therefore each new workflowitem must have a due date that is later than the due date of the previous workflowitem. 

for the case of workflow items without due date: if there are workflow items between wf1 and wf2, the due date of wf1 needs to be the baseline and the due date of wf2 must be after the due date of wf1.

**Comment by kevinbader** [comment]
@daniel-arnauer @mathiashoeld guys please don't guess here and ask the PO. I can easily come up with a different view. For example, we've discussed previously how one would reorder workflowitems during the course of a subproject. What if the individual steps each have their own deadlines but the order in which they are completed is rather flexible? Assuming _all_ of the deadlines are way into the future, this constraint would basically be a useless burden.

**Comment by BerndGewehr** [comment]
If workflow items could be hierarchically arranged by the user per drag and drop, it would be clear which of them are to be completed in serial order and which run in parallel. This way you could achieve a flexible and powerful workflow control without complex design.

**Comment by mathiashoeld** [comment]
> If workflow items could be hierarchically arranged by the user per drag and drop, it would be clear which of them are to be completed in serial order and which run in parallel. This way you could achieve a flexible and powerful workflow control without complex design.

the user can re-order workflow items freely per drag and drop, see https://github.com/openkfw/TruBudget/blob/master/doc/wiki/User-Guide/Projects/Workflowitem.md#reorder-workflowitems - they also can only be closed in sequential order as of now. as @kevinbader points out, the PO needs to decide how to deal with the new situations of deadlines and if workflow items running in parallel is a business need.

**Comment by BerndGewehr** [comment]
Just to be sure to understood well:

Currently, workflow items are a single sequential list of items.

If the user could arrange them *hierarchically* the there would be a clear order of sequential and parallel workflow items. Within this new order, a due date can be enforced as „later as its parents“ in a hierarchical tree and independent from each other for all siblings.
