### ISSUE TITLE
Check e2e-test documentation -SP 9

### ISSUE THREAD

**Issue by georgimld** [openkfw/TruBudget#769]
- [x] I have searched the [issues](https://github.com/openkfw/TruBudget/issues) of this repository and believe that this is not a duplicate.

## Summary 💡
- Make sure the e2e-test documentation is correct and that tests pass locally when using the setup and the env variables specified in the documentation
- Prepare a brownbag session afterwards

### TODO
For all todos a valid documentation should be provided (links).

- [x] e2e-tests run locally - SP 3
- [x] e2e-tests run without docker container against a trubudget environment started in a docker environment (docker-compose) - SP 1
- [x] e2e-tests run completely in docker-compose - SP 1 https://github.com/openkfw/TruBudget/issues/651 https://github.com/openkfw/TruBudget/issues/699 
- [ ] e2e-tests run completely in docker-compose but providing the cypress ui instead of running all e2e-tests instantly - SP 4 https://github.com/openkfw/TruBudget/issues/795
