### ISSUE TITLE
Document storage: permission system

### ISSUE THREAD

**Issue by galethil** [openkfw/TruBudget#771]
- [x] I have searched the [issues](https://github.com/openkfw/TruBudget/issues) of this repository and believe that this is not a duplicate.

## Summary 💡

Use multichain's permission system to restrict access to the then encrypted document link.

Permissions system based on https://www.multichain.com/developers/stream-confidentiality/
 
	1.	Each organization creates public/private key set
	2.	Private key is stored securely
	3.	Public key of each organization in published into `publicKeys` stream
	4.	Document is stored in min.io
	5.	Metadata with secret (e.g. random UUID) is stored with document in min.io
	6.	Each time workflowitem is created or updated (eg. document added, or user permission added), we will get all users with access from workflowitem
	7.	we will get all organizations from those users
	8.	For each of these organizations we will take their public keys and use  it to encrypt the document secret
	9.	These encrypted documents secrets are published in `documentsSecrets` stream with other document details
	10.	If user from second organization tries to download the document, his organization/node will use private key to decrypt document secret
	11.	Node will make HTTP request to the node with document
	12.	Decrypted secret together with document ID will be necessary to get access to document

## TODO

- [ ] Check out multichain's permission system
- [ ] Check out min.io's signed URLs
- [ ] Write down findings in issue
