### ISSUE TITLE
Subtask of 746: Frontend network table

### ISSUE THREAD

**Issue by SamuelPull** [openkfw/TruBudget#785]
- [x] I have searched the [issues](https://github.com/openkfw/TruBudget/issues) of this repository and believe that this is not a duplicate.

## Summary 💡

Frontend: 

* [ ] split `Network` table into `Organizations` and `Nodes` table
* [ ] Table for organizations, with a number of connected nodes
* [ ] When the user clicks organization, display a table with nodes (1 node per row; status or last seen time)  for that organization

- Last time seen status will be implemented in https://github.com/openkfw/TruBudget/issues/774
