### ISSUE TITLE
Write new document feature documentation 1 SP

### ISSUE THREAD

**Issue by Stezido** [openkfw/TruBudget#830]
## Summary 💡

Write new document feature documentation.
Follow up of #809 

## TODOs

- [x] master docker-compose including new document feature in docker-compose folder
- [x] describe where private/public key are generated and that 2 different keypairs are used for signing transactions and encrypting documents
- [x] check .env_examples files
- [x] storage service docker-compose.yaml - enable hot reloading of storage service
