### ISSUE TITLE
blockchain: Transecurity via SOCKS proxy of bitcoin SP 13

### ISSUE THREAD

**Issue by Stezido** [openkfw/TruBudget#831]
- [x] I have searched the [issues](https://github.com/openkfw/TruBudget/issues) of this repository and believe that this is not a duplicate.

## Summary 💡
Trubudget needs to secure connection between nodes.
Check multichain's (inherited from bitcoin) SOCKS proxy if Transecurity can be achieved.

### TODOs

- [ ] Create two simple nodes which connects throught SOCKS proxy.
- [ ] Encrypt outgoing traffic/Decrypt incoming traffic in proxy
- [ ] Include solution into Trubudget's blockchain

#### external
https://www.multichain.com/developers/creating-connecting/ - create/connect multichain nodes
https://www.multichain.com/qa/3013/https-for-json-rpc - related to this: https://bitcoin.org/en/release/v0.12.0#rpc-ssl-support-dropped and https://bitcoin.stackexchange.com/questions/39117/why-is-json-rpc-over-ssl-strongly-discouraged

https://www.multichain.com/qa/3400/what-recommended-strategy-securing-rpc-p2p-communication

#### internal
https://github.com/openkfw/TruBudget/blob/master/doc/encryption/encryption.md

### libraries
https://github.com/brozeph/simple-socks - a library that creates a socks proxy

**Comment by mayrmartin** [comment]
This issue will be closed since we found no way to achieve this ([thread in multichain form](https://www.multichain.com/qa/36704/socks-5-proxy-for-p2p-connections)) . The stream data on the chain is encrypted (#832) to ensure the authenticity of data & sender, we strongly recommend using the Multichain Enterprise edition.
