### ISSUE TITLE
Penetration tests SP5

### ISSUE THREAD

**Issue by Stezido** [openkfw/TruBudget#834]
## Summary 💡
Execute penetration tests

## TODOs

- [x] Check pen test tools
- [x] Execute pen tests locally
- [ ] Check if we could build pen test step as part of our private CI/CD 

## links

- https://www.zaproxy.org/getting-started/ - the tool we used
- https://stackoverflow.com/questions/58762658/import-zap-docker-image-in-gitlab?rq=1 
- https://www.zaproxy.org/docs/docker/about/ - ZAp docker support
- https://www.zaproxy.org/docs/docker/api-scan/ - OpenApi support for ZAP in a docker image
