### ISSUE TITLE
Add Option to Reject Workflowitem

### ISSUE THREAD

**Issue by georgimld** [openkfw/TruBudget#845]
- [ ] I have searched the [issues](https://github.com/openkfw/TruBudget/issues) of this repository and believe that this is not a duplicate.

## Summary 💡
Currently workflowitems can only be closed, which implies that the workflowitem was approved and the budget is added to the system. Currently, if a workflowitem is not approved it just stays open. A feature to close a workflowitem with a rejection it is needed. Additionaly, an option to add a comment (=exaplanation) when rejecting a workflowitem is needed.

### Possible solutions
- Adapt the "workflowitem_close" endpoint to also pass a reject/approve flag to it
- Add a new endpoint

### TODOs:

- [ ] ui: close workflowitem: open a dialog, user decides if they close the dialog by **approving** or by **rejecting** it. When reject is chosen the user must also add a comment
- [ ] api: adapt _workflowitem_close_ endpoint: add flag to approve/reject while closing (default should be **approve** -> backwards compatibility), add comment field to rejection (optional, only mandatory when rejecting)
- [ ] unit tests
- [ ] e2e-tests
