### ISSUE TITLE
Adding a link "forgot your password?" on the login screen

### ISSUE THREAD

**Issue by mayrmartin** [openkfw/TruBudget#878]
### Discussed in https://github.com/openkfw/TruBudget/discussions/854

<div type='discussions-op-text'>

<sup>Originally posted by **a-dossa** October 21, 2020</sup>
### Description
On user login page, create a "forgot your password?"   functionality, that allows to automatically reset the password via the email   adress that has been linked to the account.

### TODO
- [ ] ui: Add "forgot your password?" below the password field @ login screen
- [ ] ui: Disable the button if email service is not available/ create tooltip which informs about the missing email service
- [ ] ui: Create a password change page (similar style to login page)
             Password change fields:
                       - Email address

- [ ] ui/api: Check if user is disabled
How to check this without auth token?
- [ ] ui/email-service: Check if email exists
Create own endpoint without auth token?
- [ ] ui/email-service: Send restore password email (link)
How to create the link?

</div>

**Comment by sash9696** [comment]
Hi @mayrmartin could you please assign this issue to me

**Comment by mayrmartin** [comment]
Hi, @sash9696 thank you for having a look at this issue! 
If you have any questions don't hesitate to contact us! 😃

**Comment by galethil** [comment]
Hi @sash9696 since there is no progress on the issue I'm planning to reassign it in order to move forward with the functionality. If you already managed to implement it partly or fully just let us know.

**Comment by 27Lia** [comment]
Can I work on this?

**Comment by MartinJurcoGlina** [comment]
> Can I work on this? @mayrmartin @galethil

Hi, it's already assigned and in progress.
