### ISSUE TITLE
Easier docker-compose start script

### ISSUE THREAD

**Issue by Stezido** [openkfw/TruBudget#896]
- [x] The feature was discussed in [discussions](https://github.com/openkfw/TruBudget/discussions) of this repository.
- [x] I have searched the [issues](https://github.com/openkfw/TruBudget/issues) of this repository and believe that this is not a duplicate.

## Description 💡

Currently it's difficult to quickly setup a developer environment without carring to much about all configurations like which env vars shiould i use which services should i comment out or which docker-compose file should i use for my usecase.
The goal should be one entry point where I can decide via arguments what environment I need to setup for my specific usecase.
So a well documented script which starts the environment of Trubudget in one command where I can easily specifiy my needs as developer.

### TODOs
- [ ] create dev start script with following features:
         - choosable services (include/exclude) 
         - choose which service should be hotreloaded
         - choose if data should be persisted
         - choose if provisioning is needed
         - useful help section which is printed if the script was executed in a wrong way
         - think of useful features
- [x] create docker-compose where all services are included
- [ ] Check all available docker-compose files and try to minimize the amount of docker-compose files
