### ISSUE TITLE
Create Trubudget start script for operation teams

### ISSUE THREAD

**Issue by Stezido** [openkfw/TruBudget#905]
- [ ] The feature was discussed in [discussions](https://github.com/openkfw/TruBudget/discussions) of this repository.
- [x] I have searched the [issues](https://github.com/openkfw/TruBudget/issues) of this repository and believe that this is not a duplicate.

## Description 💡

Trubudget has already a [start script](https://github.com/openkfw/TruBudget/blob/master/scripts/development/start-dev.sh). This start script is created for developers and not flexible enough for operation teams.
This issue is about creating a new start script for operation teams similar to the developer start script including more options like a provision option or enable service options.

## TODOs

- [x] Add new Trubudget start script including more options for operation teams
- [x] default behaviour of the script should be the setup of Trubudget core components excluding provisioning and without any debug option enabled
- [ ] separate docker-compose files of Trubudget's core components and its optional services like provisioning or email service 
- [ ] check all docker-compose files and scripts. Delete them if the script can handle the setup instead (also think about a new option if its not yet possible to do it via script)
- [ ] check documentation update deprecated links and reference the new script in the operations/installation guide

### Script options for operation teams
-  `--provision` - start provisioning service and generate test data for the setup
- `--enable-service [service-name]` - enable the service specified (include the docker-compose.yml of the specific service)

**Comment by Stezido** [comment]
The developer script was created in #901
