### ISSUE TITLE
misleading environment variables

### ISSUE THREAD

**Issue by Stezido** [openkfw/TruBudget#928]
- [x] I have searched the [issues](https://github.com/openkfw/TruBudget/issues) of this repository and believe that this is not a duplicate.

## Description 😯

In the email-notification-service there are several env vars. Two of them are called MODE and LOG_LEVEL. I have expected if I set the MODE to "DEBUG" the log_level also changes.

### Suggestion
Rename MODE to AUTHENTICATION or AUTHENTICATION_METHOD with values "JWT" or "none".

### TODOs

- [x] Rename env var
- [ ] Check Deployments of latest version

## Your Environment 🌎

| Tech            | Version |
| --------------- | ------- |
| Email-Service   | v1.24.0  |
