### ISSUE TITLE
Disable the Test/Prod option for the Production environment (SP 2)

### ISSUE THREAD

**Issue by Stezido** [openkfw/TruBudget#954]
### Discussed in https://github.com/openkfw/TruBudget/discussions/873

<div type='discussions-op-text'>

<sup>Originally posted by **phpai** March 22, 2019</sup>
In GitLab by @jnogueira on Mar 14, 2019, 20:27

Currently, Test and Production environment are in the same server. Therefore, if you have a problem in this particular server, both enviroments can be lose.

This issue considers that there is a seggregation, one production server and other server for everything else at least.
In this scenario, it is important to disable the feature Test/Prod on the Production server. The Test/Prod combo still can be useful in the other environment (test, development, validation...), but no for Production.

Therefore, this issue requires to disable the Test/Prod feature for the Production environment.

![image (1)](https://user-images.githubusercontent.com/20185479/54906298-44c7d380-4ee3-11e9-9d68-5531686c7791.png)
</div>

### TODOs

- [ ] Modify frontend : Remove the option to switch between environments , Merge env variables
- [ ] Write documentation how to update to the latest version where the environments PROD/TEST are split. (spawn additional frontend, server additional URL, api/blockchain can be used as is)
- [ ] Test the documentation
