### ISSUE TITLE
Each user should sign his/her action with his/her own key (SP 8)

### ISSUE THREAD

**Issue by Stezido** [openkfw/TruBudget#955]
### Discussed in https://github.com/openkfw/TruBudget/discussions/858

<div type='discussions-op-text'>

<sup>Originally posted by **Stezido** June  8, 2021</sup>
## Summary 💡
Currently each organization has a walletaddress with private key which is used to sign every transaction the organization made.
It should be possible to sign a transaction with the user's walletaddress/privkey.

Maybe a network can switch between "Sign with organization wallet address" and "Sign with user wallet address" ?

## Requirements

- Each transaction can be signed with the user's wallet address
- Each network (master-node) can decide which signing method should be used on the whole network
- Private key of user is only accessible by the user herself

## TODOs

- [ ] Check multichain's publishfrom command
- [ ] Check how it's currently done (signing with organization's wallet address)
- [ ] Create a tech-arch picture/ adr which describes the implementation of the new solution
- [ ] Discuss the solution with the team
- [ ] Implement solution

</div>
