### ISSUE TITLE
An organization can modify users of other organizations SP 0.5

### ISSUE THREAD

**Issue by Stezido** [openkfw/TruBudget#983]
- [x] I have searched the [issues](https://github.com/openkfw/TruBudget/issues) of this repository and believe that this is not a duplicate.

## Description 😯

If two organizations are part of a network and both have created users, the root user of one organization can modify permissions of users of another organization or can even deactivate users of another organization.

I would expect that the root user has only permissions to do user permission changes for his/her own organization.

### How to reproduce 🕹

1. Start a network with 2 organizations
2. 2. login with root user of orga1
2. create 1 user organization 
2. login with root user of orga2
1. deactivate previously created user

## TODOs

- [x] Check if it is possible to disable users from a different Organization as root user
- [x] Check if group-permission enable a user to do to much (cross orga permission, user disable...)  Could be solved by one of:
- Group permission do not include user related intents or
- Assign groups to an organization
- Use Organization of specific User of a group to decide on user related permissions
- or find another solution
- [x]  Check if groups need to belong to an Organization

## Your Environment 🌎

| Tech            | Version |
| --------------- | ------- |
| Frontend        | v1.25.0 |
| API             | v1.25.0  |
| Blockchain      | v1.25.0  |

**Comment by daniel-arnauer** [comment]
Cannot re-create this issue for disabling users of other organizations (since there is an explicit check in the API for the organizations). However, it is possible to change the user permissions of projects that do not belong to the root users organization (frontend prevents that, but API allows to do modifications). So the organization check should be applied to project.intent.grantPermission and project.intent.revokePermission and all other similiar intens too. 

With the search term `.organization !==`, the implementations of this security rule can be found

**Comment by daniel-arnauer** [comment]
Furthermore, **groups do not belong to organizations** (but users do). This is also a big security concern and is also a breaking change (breaking old multichain data)

**Comment by daniel-arnauer** [comment]
Issues to resolve:

- Root user of any node can edit the password of any user because the API checks the password of the requesting user, not the target user (UI and API)


- Root user can execute some project/subproject/wf -intents via API (but not frontend). 
For instance: 

1. root user of Slave can assign new user for project of master node (only API)
2. root user of Slave can change description of subproject of master node (UI and API)
3. root user of Slave can change project permissions of master node projects (only API)
4. root user of Slave can add budget in project that is created by master node (UI and API)
